### ISSUE TITLE
Does not work

### ISSUE THREAD

**Issue by fizerkhan** [terrierscript/grunt-cssjoin#1]
@suisho Thanks for your great work.

I am using Yeoman 1.0 Beta for my Web application which has 

```
webapp
     app
          components
          styles
                index.scss
     dist
          styles
                index.css
    Gruntfile.js
```

I used SASS for stylesheets. index.scss file includes other third party css files like 

```
   @import url(../components/alertify/themes/alertify.core.css);
   @import url(../components/alertify/themes/alertify.default.css);
   @import url(../components/select2/select2.css);
   @import url(../components/jquery-file-upload/css/jquery.fileupload-ui.css);
```

The grunt tasks compiles this sass into **dist/styles/index.css**. I included **cssjoin** grunt task to join all import css file. My configuration as follows

```
    cssjoin : {
        path_option :{
            options: {
                path : ['app/styles/']
            },
            files: {
                'dist/styles/index.css': ['dist/styles/index.css'],
            },
        }
    },
```

But final CSS file still has @import statement. Am i missing anything?

**Comment by suisho** [comment]
@fizerkhan Thank you for report issue.

First, `cssjoin` module couldn't resolve pattern like `@import url(./path/to)` and fix this problem.

And second, this project's document has mistake. :fearful:
That is `path` is missed and correct is `paths`.

```
            options: {
                paths : ['app/styles/']
            },
```

Please rewrite your Gruntfile.

**Comment by fizerkhan** [comment]
It works great. 
I have more than one files in my dist folder and i want to apply cssjoin all files. How do i apply cssjoin for set of files and i want to save them in same file?

Moreover, **compass** replaces all my  **@import "./path/to"** statements with **@import url(./path/to)**. Is there any way to fix in your side?

**Comment by suisho** [comment]
If you want convert all file, you write Gruntfile

```
grunt.initConfig({
  cssjoin: {
      path_option :{
            options: {
                path : ['app/styles/']
            },
      files:  grunt.file.expandMapping(["dist/**/*.css"]),
    }
  }
})
```

this use grunt's expandMapping function.

And @import url(.path/to) is already fiixed and enable converting

**Comment by fizerkhan** [comment]
@suisho Thanks for the fix. It is awesome. It works well Yeoman.

Above comment, change  **path** to **paths**  :)
